export * from "./AboutUs/AboutUs";
export * from "./Catalog/Catalog";
export * from "./Faq/Faq";
export * from "./OurTeam/OurTeam";
export * from "./Quiz/Quiz";
export * from "./Welcome/Welcome";
export * from "./Contact/Contact";
export * from "./Product/Product";
export * from "./Feedback/Feedback";
